configfile: "config/config.yaml"

SAMPLES = config["samples"]
READS = ["1", "2"]

rule all:
    input:
        "results/qc/raw/multiqc_report.html",
        "results/qc/trimmed/multiqc_report.html",
        expand("data/trimmed/{sample}_{read}.trimmed.fastq.gz", sample=SAMPLES, read=READS)

#rule all:
#    input:
#        "results/qc/raw/multiqc_report.html",
#        "results/qc/trimmed/multiqc_report.html",
#        expand("data/trimmed/{sample}_{read}.trimmed.fastq.gz", sample=SAMPLES, read=READS),
#        expand("results/aligned/{sample}.bam", sample=SAMPLES),
#        expand("results/aligned/{sample}.bam.bai", sample=SAMPLES),
#        "results/counts/counts_matrix.txt",
#        "results/deseq2/DE_results.csv",
#        "results/deseq2/PCA_plot.png",
#        "results/deseq2/Volcano_plot.png",
#        "results/deseq2/Heatmap_top50.png",
#        "results/deseq2/GO_dotplot_UP.png",
#        "results/deseq2/GO_dotplot_DOWN.png"

rule fastqc_raw:
    input:
        "data/raw/{sample}_{read}.fastq.gz"
    output:
        html="results/qc/raw/fastqc/{sample}_{read}_fastqc.html",
        zip="results/qc/raw/fastqc/{sample}_{read}_fastqc.zip"
    conda:
        "envs/qc.yaml"
    threads: 2
    shell:
        "mkdir -p results/qc/raw/fastqc && "
        "fastqc {input} --outdir results/qc/raw/fastqc --threads {threads}"

rule multiqc_raw:
    input:
        expand("results/qc/raw/fastqc/{sample}_{read}_fastqc.html", sample=SAMPLES, read=READS)
    output:
        "results/qc/raw/multiqc_report.html"
    conda:
        "envs/qc.yaml"
    shell:
        "mkdir -p results/qc/raw && "
        "multiqc results/qc/raw/fastqc --outdir results/qc/raw --filename multiqc_report.html"

rule fastp:
    input:
        r1="data/raw/{sample}_1.fastq.gz",
        r2="data/raw/{sample}_2.fastq.gz"
    output:
        r1="data/trimmed/{sample}_1.trimmed.fastq.gz",
        r2="data/trimmed/{sample}_2.trimmed.fastq.gz",
        html="results/qc/fastp/{sample}_fastp.html",
        json="results/qc/fastp/{sample}_fastp.json"
    conda:
        "envs/qc.yaml"
    threads: 8
    shell:
        "mkdir -p data/trimmed results/qc/fastp && "
        "fastp "
        "--in1 {input.r1} --in2 {input.r2} "
        "--out1 {output.r1} --out2 {output.r2} "
        "--detect_adapter_for_pe "
        "--cut_front --cut_tail "
        "--cut_window_size 4 --cut_mean_quality 20 "
        "--length_required 36 "
        "--thread {threads} "
        "--html {output.html} --json {output.json}"

rule fastqc_trimmed:
    input:
        "data/trimmed/{sample}_{read}.trimmed.fastq.gz"
    output:
        html="results/qc/trimmed/fastqc/{sample}_{read}.trimmed_fastqc.html",
        zip="results/qc/trimmed/fastqc/{sample}_{read}.trimmed_fastqc.zip"
    conda:
        "envs/qc.yaml"
    threads: 2
    shell:
        "mkdir -p results/qc/trimmed/fastqc && "
        "fastqc {input} --outdir results/qc/trimmed/fastqc --threads {threads}"

rule multiqc_trimmed:
    input:
        expand("results/qc/trimmed/fastqc/{sample}_{read}.trimmed_fastqc.html", sample=SAMPLES, read=READS)
    output:
        "results/qc/trimmed/multiqc_report.html"
    conda:
        "envs/qc.yaml"
    shell:
        "mkdir -p results/qc/trimmed && "
        "multiqc results/qc/trimmed/fastqc --outdir results/qc/trimmed --filename multiqc_report.html"

rule star_index:
    input:
        fasta=config["reference_fasta"],
        gtf=config["reference_gtf"]
    output:
        directory(config["star_index_dir"])
    conda:
        "envs/align.yaml"
    threads: 8
    params:
        sjdb_overhang=lambda wc: config.get("sjdb_overhang", 99),
        sa_index_bases=lambda wc: config.get("genomeSAindexNbases", 14)
    shell:
        "mkdir -p {output} && "
        "STAR --runMode genomeGenerate "
        "--runThreadN {threads} "
        "--genomeDir {output} "
        "--genomeFastaFiles {input.fasta} "

